// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNSxQmsjMJRRDniw6K6NW8O2_0TI-m8Q',
    appId: '1:533738593546:android:9f0ca6ef90342c4cc16ef3',
    messagingSenderId: '533738593546',
    projectId: 'smart-auth-mca-igit',
    storageBucket: 'smart-auth-mca-igit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbowsm254h6cA_zinnuEBp3FQ0ZRwYg5E',
    appId: '1:533738593546:ios:6edd6273dd49b71bc16ef3',
    messagingSenderId: '533738593546',
    projectId: 'smart-auth-mca-igit',
    storageBucket: 'smart-auth-mca-igit.appspot.com',
    iosBundleId: 'com.example.testFingerprint',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxtlD7NayqHJbkXLtnGhXy5UzAMwAKd7k',
    appId: '1:533738593546:web:643c060a6fa2001dc16ef3',
    messagingSenderId: '533738593546',
    projectId: 'smart-auth-mca-igit',
    authDomain: 'smart-auth-mca-igit.firebaseapp.com',
    storageBucket: 'smart-auth-mca-igit.appspot.com',
    measurementId: 'G-6DMXNSCVVD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbowsm254h6cA_zinnuEBp3FQ0ZRwYg5E',
    appId: '1:533738593546:ios:6edd6273dd49b71bc16ef3',
    messagingSenderId: '533738593546',
    projectId: 'smart-auth-mca-igit',
    storageBucket: 'smart-auth-mca-igit.appspot.com',
    iosBundleId: 'com.example.testFingerprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxtlD7NayqHJbkXLtnGhXy5UzAMwAKd7k',
    appId: '1:533738593546:web:96f9703a88ced73cc16ef3',
    messagingSenderId: '533738593546',
    projectId: 'smart-auth-mca-igit',
    authDomain: 'smart-auth-mca-igit.firebaseapp.com',
    storageBucket: 'smart-auth-mca-igit.appspot.com',
    measurementId: 'G-TJM68J0PDC',
  );

}